### ISSUE TITLE
Fix ingredients UI

### ISSUE THREAD

**Issue by Lucytheanimefan** [Lucytheanimefan/ECE458-hypothetical-meals#18]
Updating and creating ingredients should be on the same admin-only page.

Ingredients page, which is accessible to all so and where users can add/remove ingredients to cart (@amanocha I'm thinking this is where you should have that add to cart button, not in the profile page), should be separate.

**Comment by dy46** [comment]
Should we have the users be able to add/remove ingredients from the ingredients page? I think it makes more sense for them to be able to add it from the ingredient detail page.

**Comment by dy46** [comment]
Teddy and I were thinking the ingredients page should just be a place for the user to search and filter ingredients.

**Comment by Lucytheanimefan** [comment]
That makes sense. Come to think of it, I guess that's how Amazon does it too.
